test_script:
- appveyor version
- ps: $ErrorActionPreference = "Stop"
- ps: if(-not (Test-Path "$env:APPDATA\Windows Azure Powershell\AzurePSDataCollectionProfile.json")) { throw "AzurePSDataCollectionProfile.json does not exist."; }
- ps: |
    Write-Host "Testing new cmdlets"
    Get-Command Connect-AzAccount
    Get-Command Get-AzRmStorageContainer
    Write-Host "Testing cmdlets in compatibility mode"
    Enable-AzureRmAlias
    Get-Command Login-AzureRmAccount
    Get-Command Get-AzureRmApiManagementBackend

build: off
